#!/bin/bash

## the purpose of this script is to prefix the PIC specific compiler options
## produced by libtool with nvcc's compiler fowrading flag.

shopt -s extglob

last_O=""	# nvcc bitches about -O being specified multiple times.
args=""
while (( "$#" )); do
	if [[ "$1" =~ -.PIC ]] ; then
		args="$args -Xcompiler $1"
	elif [[ "$1" == "-ggdb3" ]] ; then
		args="$args -g"
	elif [[ "$1" =~ -O. ]] ; then
		last_O="$1"
	elif [[ "$1" == "-std=gnu++0x" ]] ; then	# new standard is not available in nvcc.
		true;
	elif [[ "$1" == "-Wreturn-type" ]] ; then	# not available in nvcc?
		true;
	else
		#echo "plain forward: '$1'."
		args="$args $1"
	fi
	shift
done

args="$args $last_O"

# #switch to cc 200 for AILA.cu, KDIS_SL.cu, presort.cu
# if [[ "$args" == *"AILA.cu"* || "$args" == *"KDIS_SL.cu"* || "$args" == *"presort.cu"* ]] ; then
# 	args=$(echo "$args" | sed -e "s/12/20/g")
# fi

echo
echo $args
echo
echo
nvcc $args #2> /tmp/nvccwrapper-log
ret=$?

#cat /tmp/nvccwrapper-log >> /tmp/ptxas.log
#grep -e "error" -e "fatal" -e "warning" /tmp/nvccwrapper-log

exit $ret
